### ISSUE TITLE
Not a bug, a question (maybe feature suggestion). I couldn't find any other way to contact you.

### ISSUE THREAD

**Issue by longshadowdev** [AF-1/lms-customstartstoptimes#1]
Hello, I just wanted to ask if it's possible already (if not consider a feature suggestion) to skip middle parts of a track?

I often find with my albums the last track is comprised of a real song (that's listed on the track list on the CD), then some minutes of silence, then a 'secret song'. It'd be cool if the silence could be skipped over automatically.

I traditionally just split the songs so that the secret one can have a name and the silence is gone, however this leads to both tracks being not compliant with MusicBrainz and other services, and causes issues. A plugin like this would be a better way to solve the issue.

Apologies for not using the template, my question/feedback wouldn't fit in to that structure.

Thanks

**Comment by AF-1** [comment]
I promise I'll have a look.
BTW you can find me on the LMS forum. Some plugins have support threads [there](https://forums.slimdevices.com/forum/user-forums/3rd-party-software/113445-announce-custom-start-stop-times).

**Comment by AF-1** [comment]
v1.1.0 should allow you to [skip a specific part of the song](https://github.com/AF-1/lms-customstartstoptimes#skip-part-of-the-song).

**Comment by longshadowdev** [comment]
Excellent work my friend! I appreciate it a lot!

**Comment by longshadowdev** [comment]
@AF-1 hey, just a little extra feedback.

1 - It works perfectly, thank you!
2 - The documentation could remove a small amount of ambiguity. The tag that needs to be added/modified is called `COMMENT` not `COMMENTS`.

Once again thank you!
